<?php

namespace Io\Prosopo\Procaptcha\Vendors;

// autoload_psr4.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('Prosopo\Views\PrivateClasses\\' => array($vendorDir . '/prosopo/views/private-classes'), 'Prosopo\Views\\' => array($vendorDir . '/prosopo/views/src'));
