<?php

// autoload_static.php @generated by Composer
namespace Io\Prosopo\Procaptcha\Vendors\Composer\Autoload;

class ComposerStaticInit043dd16cfbc09f98741d61dc32af3bc2
{
    public static $prefixLengthsPsr4 = array('P' => array('Prosopo\Views\PrivateClasses\\' => 29, 'Prosopo\Views\\' => 14));
    public static $prefixDirsPsr4 = array('Prosopo\Views\PrivateClasses\\' => array(0 => __DIR__ . '/..' . '/prosopo/views/private-classes'), 'Prosopo\Views\\' => array(0 => __DIR__ . '/..' . '/prosopo/views/src'));
    public static $classMap = array('Io\Prosopo\Procaptcha\Vendors\Composer\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php');
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit043dd16cfbc09f98741d61dc32af3bc2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit043dd16cfbc09f98741d61dc32af3bc2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit043dd16cfbc09f98741d61dc32af3bc2::$classMap;
        }, null, ClassLoader::class);
    }
}
