<?php

namespace Io\Prosopo\Procaptcha\Vendors;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit043dd16cfbc09f98741d61dc32af3bc2
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('Io\Prosopo\Procaptcha\Vendors\ComposerAutoloaderInit043dd16cfbc09f98741d61dc32af3bc2', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \Io\Prosopo\Procaptcha\Vendors\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInit043dd16cfbc09f98741d61dc32af3bc2', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\Io\Prosopo\Procaptcha\Vendors\Composer\Autoload\ComposerStaticInit043dd16cfbc09f98741d61dc32af3bc2::getInitializer($loader));
        $loader->register(\true);
        return $loader;
    }
}
// autoload_real.php @generated by Composer
\class_alias('Io\Prosopo\Procaptcha\Vendors\ComposerAutoloaderInit043dd16cfbc09f98741d61dc32af3bc2', 'ComposerAutoloaderInit043dd16cfbc09f98741d61dc32af3bc2', \false);
