<?php

namespace Io\Prosopo\Procaptcha\Vendors;

// autoload_classmap.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('Io\Prosopo\Procaptcha\Vendors\Composer\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php');
